### ISSUE TITLE
Problem in digiwf mit complience check

### ISSUE THREAD

**Issue by hupling** [it-at-m/digiwf-template#26]
https://github.com/it-at-m/digiwf-core/actions/runs/9282956381/job/25542108097?pr=1731

Ich habe auch versucht https://github.com/it-at-m/sps/blob/main/.github/workflows/build.yaml von Version 2.7.2 auf 2.7.3 zu updaten. Jetzt geht beides nicht mehr. 

zur Info @simonhir

Frage an @eidottermihi ist gerade eine API down?

**Comment by simonhir** [comment]
Problem scheint in dem Fall von DigiWF durch ein `npm update` reinzukommen.

Siehe https://github.com/it-at-m/digiwf-core/pull/1735/commits/8804ff2566feb3414c235e3ff9a33f5172ef14f9

Fehlermeldung:

```
ERROR:root:Unknown Exception was hit, please repo this to https://github.com/advanced-security/policy-as-code
 _____  _   _   ___   _____ _____                       _ _                      
ERROR:root:DependencyAlert.__init__() missing 2 required positional arguments: 'state' and 'severity'
|  __ \| | | | / _ \ /  ___/  __ \                     | (_)                     
| |  \/| |_| |/ /_\ \\ `--.| /  \/ ___  _ __ ___  _ __ | |_  __ _ _ __   ___ ___ 
| | __ |  _  ||  _  | `--. \ |    / _ \| '_ ` _ \| '_ \| | |/ _` | '_ \ / __/ _ \
| |_\ \| | | || | | |/\__/ / \__/\ (_) | | | | | | |_) | | | (_| | | | | (_|  __/
 \____/\_| |_/\_| |_/\____/ \____/\___/|_| |_| |_| .__/|_|_|\__,_|_| |_|\___\___|
                                                 | |                             
                                                 |_|         v2.7.3
    GitHub Advanced Security Policy as Code by GeekMasher
INFO:root:Dependencies from Pull Request

GitHub Repository :: it-at-m/digiwf-core
GitHub Instance :: https://github.com/
GitHub Reference (branch/pr) :: refs/pull/1735/merge
Policy as Code
Dependency Graph
  Dependencies from Pull Request
  Error: Unknown Exception was hit, please repo this to https://github.com/advanced-security/policy-as-code
  Error: DependencyAlert.__init__() missing 2 required positional arguments: 'state' and 'severity'
  ERROR:root:Unknown Exception was hit, please repo this to https://github.com/advanced-security/policy-as-code
Dependency Graph Results - Licensing
  ERROR:root:DependencyAlert.__init__() missing 2 required positional arguments: 'state' and 'severity'
  Dependencies from Pull Request
  Error: Unknown Exception was hit, please repo this to https://github.com/advanced-security/policy-as-code
  Error: DependencyAlert.__init__() missing 2 required positional arguments: 'state' and 'severity'
  INFO:root:Total unacceptable alerts :: 2
  ERROR:root:Unacceptable Threshold of Risk has been hit!
Summary
  Total unacceptable alerts :: 2
  Error: Unacceptable Threshold of Risk has been hit!
  Error: Process completed with exit code 1.
```

**Comment by eidottermihi** [comment]
ich hab die Verwendung von diesem "Tool" nicht eingeführt - evtl. sollte die Reife dieses Tools schon nochmal hinterfragt werden, denn es produziert mehr Fehler/False Positives, als es Nutzen schafft.

Ansonsten jetzt konkret ist wohl das zielführend was in der Fehlermeldung steht:

`Unknown Exception was hit, please repo this to https://github.com/advanced-security/policy-as-code`

**Comment by simonhir** [comment]
> ich hab die Verwendung von diesem "Tool" nicht eingeführt - evtl. sollte die Reife dieses Tools schon nochmal hinterfragt werden, denn es produziert mehr Fehler/False Positives, als es Nutzen schafft.

Sehe ich auch so, gibt dazu intern auch https://git.muenchen.de/ccse/ospo/-/issues/171

**Comment by hupling** [comment]
kommt vermutlich von @a-m-zill und der arbeitet nicht mehr bei der LHM 😢

**Comment by eidottermihi** [comment]
interne Diskussion bzgl. allgemein Tooleinsatz hinterfragen/überdenken: https://git.muenchen.de/ccse/ospo/-/issues/381

entsprechende Diskussionen bitte hier intern, danke!

**Comment by hupling** [comment]
wird intern weiter diskutiert.
